version: '3.1'

services:

  db:
    image: mysql:8.0.26
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agora
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    expose:
      - 3336
    ports:
      - 3336:3306
