# https://davidgarcia.dev/posts/how-to-split-open-api-spec-into-multiple-files/
# https://nordicapis.com/7-open-source-openapi-documentation-generators/
openapi: 3.0.0
info:
  title: Agora
  version: '0.1'
servers:
  -
    url: http://localhost
    description: Local servcer
paths:

  /api/v1/users/login:
    $ref: "./paths/users/login.yaml"

  /api/v1/users/register:
    $ref: "./paths/users/register.yaml"
    
  /api/v1/users:
    $ref: "./paths/users.yaml"

  /api/v1/users/login/guest:
    $ref: "./paths/users/login_guest.yaml"

  /api/v1/users/token/renew:

  /api/v1/users/{user_id}:

  /api/v1/campaigns:

  /api/v1/campaigns/{campaign_id}:

  /api/v1/campaigns/{campaign_id}/proposition-results:

  /api/v1/campaigns/{campaign_id}/users/{campaign_user_id}:

  /api/v1/campaigns/{campaign_id}/users:

  /api/v1/campaigns/{campaign_id}/users/{campaign_user_id}/invite:

  /api/v1/campaigns/{campaign_id}/propositions:

  /api/v1/campaigns/{campaign_id}/propositions/{proposition_id}:

  /api/v1/campaigns/{campaign_id}/status:

  /api/v1/campaigns/{campaign_id}/init-ranking:

  /api/v1/campaigns/{campaign_id}/update-ranking:

  /api/v1/campaigns/{campaign_id}/own-proposition-results:

  /api/v1/campaigns/{campaign_id}/init-elo-ranking:

  /api/v1/campaigns/{campaign_id}/elo-duel-result:

  /api/v1/campaigns/{campaign_id}/elo-ranking:

  /api/v1/campaigns/{campaign_id}/elo-random-propositions:

components:

  securitySchemes:
    bearer:
      scheme: bearer
      type: http
      bearerFormat: JWT

  schemas:
    SomeType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string