# https://davidgarcia.dev/posts/how-to-split-open-api-spec-into-multiple-files/
# https://nordicapis.com/7-open-source-openapi-documentation-generators/
openapi: 3.0.0
info:
  title: Agora
  version: '0.1'
servers:
  -
    url: http://localhost
    description: Local servcer
paths:

  /api/v1/users/login:
    $ref: "./paths/users/login.yaml"

  /api/v1/users/register:
    $ref: "./paths/users/register.yaml"
    
  /api/v1/users:
    $ref: "./paths/users.yaml"

  /api/v1/users/login/guest:
    $ref: "./paths/users/login_guest.yaml"

  /api/v1/users/token/renew:
    $ref: "./paths/users/token_renew.yaml"

  /api/v1/users/{user_id}:
    $ref: "./paths/users/user_id.yaml"

  /api/v1/campaigns:
    $ref: "./paths/campaigns.yaml"

  /api/v1/campaigns/{campaign_id}:
    $ref: "./paths/campaigns/campaign_id.yaml"

  /api/v1/campaigns/{campaign_id}/proposition-results:
    $ref: "./paths/campaigns/proposition_results.yaml"

  /api/v1/campaigns/{campaign_id}/users:
    $ref: "./paths/campaigns/users.yaml"

  /api/v1/campaigns/{campaign_id}/users/{campaign_user_id}:
    $ref: "./paths/campaigns/users/campaign_user_id.yaml"

  /api/v1/campaigns/{campaign_id}/users/{campaign_user_id}/invite:
    $ref: "./paths/campaigns/users/campaign_user_id_invite.yaml"

  /api/v1/campaigns/{campaign_id}/propositions:
    $ref: "./paths/campaigns/propositions.yaml"

  /api/v1/campaigns/{campaign_id}/propositions/{proposition_id}:
    $ref: "./paths/campaigns/propositions/proposition_id.yaml"

  /api/v1/campaigns/{campaign_id}/status:
    $ref: "./paths/campaigns/status.yaml"

  /api/v1/campaigns/{campaign_id}/init-ranking:
    $ref: "./paths/campaigns/init_ranking.yaml"

  /api/v1/campaigns/{campaign_id}/update-ranking:
    $ref: "./paths/campaigns/update_ranking.yaml"

  /api/v1/campaigns/{campaign_id}/own-proposition-results:
    $ref: "./paths/campaigns/own_proposition_results.yaml"

  /api/v1/campaigns/{campaign_id}/init-elo-ranking:
    $ref: "./paths/campaigns/init_elo_ranking.yaml"

  /api/v1/campaigns/{campaign_id}/elo-duel-result:
    $ref: "./paths/campaigns/elo_duel_ranking.yaml"

  /api/v1/campaigns/{campaign_id}/elo-ranking:
    $ref: "./paths/campaigns/elo_ranking.yaml"

  /api/v1/campaigns/{campaign_id}/elo-random-propositions:
    $ref: "./paths/campaigns/elo_random_propositions.yaml"

components:

  securitySchemes:
    bearer:
      scheme: bearer
      type: http
      bearerFormat: JWT

  schemas:
    SomeType:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
