@startuml

title Data model

class "users" {
  * id
  * first_name
  * last_name
  * password
  * email
  --
}

class "campaigns" {
  * id
  * title
  * description
  * start_date
  * end_date
  * status
  * owner_user_id
  --
}

class "propositions" {
  * id
  * campaign_id
  * creator_user_id
  * payload
  --
}

class "users_propositions_results" {
  * id
  * campaign_id
  * proposition_id
  * user_id
  * rank
  --
}

class "users_propositions_elo_results" {
  * id
  * campaign_id
  * proposition_id
  * user_id
  * elo_score
  --
}



campaigns --|> users
propositions --|> campaigns

@enduml
